Remove confusing comments related to pipes
The comments about the typing issues aren't much
use now.  We have a workaround and the old
comments can lead to confusion.

For posterity, these are the kind of compilation errors
we get with the old `obj << py_value` code:

```
ext/server/pipe.cpp: In instantiation of 'void PyTango::Pipe::__append_scalar(T&, const string&, boost::python::api::object&) [with T = Tango::DevicePipeBlob; long int tangoTypeConst = 8; std::string = std::__cxx11::basic_string<char>]':
ext/server/pipe.cpp:196:56:   required from 'void PyTango::Pipe::append_scalar(Tango::DevicePipeBlob&, const string&, boost::python::api::object&) [with long int tangoTypeConst = 8; std::string = std::__cxx11::basic_string<char>]'
ext/server/pipe.cpp:318:2:   required from 'void PyTango::Pipe::__append(T&, const string&, boost::python::api::object&, Tango::CmdArgType) [with T = Tango::DevicePipeBlob; std::string = std::__cxx11::basic_string<char>]'
ext/server/pipe.cpp:419:11:   required from 'void PyTango::Pipe::__set_value(T&, boost::python::api::object&) [with T = Tango::DevicePipeBlob]'
ext/server/pipe.cpp:414:21:   required from 'void PyTango::Pipe::__set_value(T&, boost::python::api::object&) [with T = Tango::Pipe]'
ext/server/pipe.cpp:426:41:   required from here
ext/server/pipe.cpp:150:10: error: ambiguous overload for 'operator<<' (operand types are 'Tango::DevicePipeBlob' and 'TangoScalarType' {aka 'char*'})
  150 |      obj << value;
      |      ~~~~^~~~~~~~
In file included from /opt/conda/envs/py3.7-tango9.4.0/include/tango/client/devapi.h:468,
                 from /opt/conda/envs/py3.7-tango9.4.0/include/tango/client/dbapi.h:32,
                 from /opt/conda/envs/py3.7-tango9.4.0/include/tango/tango.h:114,
                 from /proj/ext/pytgutils.h:15,
                 from ext/server/pipe.cpp:14:
/opt/conda/envs/py3.7-tango9.4.0/include/tango/client/DevicePipe.h:619:19: note: candidate: 'Tango::DevicePipeBlob& Tango::DevicePipeBlob::operator<<(const DevBoolean&)'
  619 |  DevicePipeBlob & operator << (const DevBoolean &);
      |                   ^~~~~~~~
/opt/conda/envs/py3.7-tango9.4.0/include/tango/client/DevicePipe.h:629:19: note: candidate: 'Tango::DevicePipeBlob& Tango::DevicePipeBlob::operator<<(char* const&)'
  629 |  DevicePipeBlob & operator << (const DevString &);
      |                   ^~~~~~~~
/opt/conda/envs/py3.7-tango9.4.0/include/tango/client/DevicePipe.h:632:19: note: candidate: 'Tango::DevicePipeBlob& Tango::DevicePipeBlob::operator<<(const string&)'
  632 |  DevicePipeBlob & operator << (const std::string &);
      |                   ^~~~~~~~
/opt/conda/envs/py3.7-tango9.4.0/include/tango/client/DevicePipe.h:1156:17: note: candidate: 'Tango::DevicePipeBlob& Tango::operator<<(Tango::DevicePipeBlob&, T&) [with T = char*]'
 1156 | DevicePipeBlob &operator<<(DevicePipeBlob &,T &);
      |                 ^~~~~~~~
/opt/conda/envs/py3.7-tango9.4.0/include/tango/client/DevicePipe.h:1159:17: note: candidate: 'Tango::DevicePipeBlob& Tango::operator<<(Tango::DevicePipeBlob&, T*) [with T = char]'
 1159 | DevicePipeBlob &operator<<(DevicePipeBlob &,T *);
      |                 ^~~~~~~~
```